### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by h4ck3rm1k3** [flosskosova/openstreetmap_cleanup#21]
# Here are ones to check :
- [манастир Високи Дечани](https://www.openstreetmap.org/way/223823520)
- [радар](https://www.openstreetmap.org/way/400234107)
- [Црквина - Небеске столице](https://www.openstreetmap.org/node/1356885949)

see changes from today 
https://github.com/flosskosova/openstreetmap_cleanup/commit/0008765958d5ae0ee2c10e352758aabc44aec294#diff-0008bd64bca3cf32304ab7293617d71cR1198

**Comment by MarcKosova** [comment]
done (2 of 3 points are located in the Republic of Serbia, 1 has been changed by me correctly)
